version: '3'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      #MYSQL_DATABASE: your_database
      #MYSQL_USER: your_user
      #MYSQL_PASSWORD: changeme
    ports:
      - 3306:3306
    command: ["--default-authentication-plugin=mysql_native_password", "--bind-address=0.0.0.0"]

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - mysql:db
    ports:
      - "8080:80"
    environment:
      PMA_ARBITRARY: 1

  setup_db:
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - mysql
    depends_on:
      - mysql
    command: ["bash", "-c", "sleep 20 && python setup_db.py"]
